version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped

  web:
    build:
      context: angry_app/
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}


  worker:
    build:
      context: angry_app/
      dockerfile: docker/Dockerfile
    command: celery -A celery_app worker
    depends_on:
      - redis
    environment:
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
